version: '3'

services:
  zookeeper:
    image: 'ubuntu/zookeeper:edge'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    container_name: zookeeper-server
  kafka:
    image: 'ubuntu/kafka:3.1-22.04_beta'
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-server:2181
      ZOOKEEPER_HOST: host.docker.internal
      TZ: CST
    container_name: kafka-server

networks:
  default:
    external: true
    name: app-tier